name: openriak-docs

services:
  openriak-docs-web:
    image: httpd:latest
    container_name: openriak-docs-web
    ports:
      - "3001:80"      # website
    volumes:
       - ../build:/usr/local/apache2/htdocs:ro
    restart: "no"          # don't restart the container
